require "faker"
require_relative './classes/teams.rb'
require_relative './classes/players.rb'
require_relative './classes/game.rb'
def seed
    #These are the empty arrays to contain the player details generated by faker
    team_1_players = []
    team_2_players = []
    team_3_players = []
    team_4_players = []

    #This is the loop to generate the player names from faker
    for i in 1..5
        team_1_players << Player.new(Faker::Sports::Football.unique.player, i)
    end
    for i in 1..5
        team_2_players << Player.new(Faker::Sports::Football.unique.player, i)
    end
    for i in 1..5
        team_3_players << Player.new(Faker::Sports::Football.unique.player, i)
    end
    for i in 1..5
        team_4_players << Player.new(Faker::Sports::Football.unique.player, i)
    end

    team_1_captain = "Gigi Buffon"
    team_2_captain = "Fabian Barthez"
    team_3_captain = "Rene Higuita"
    team_4_captain = "Mark Schwarzer"

    #This will determine who wins the coin toss
    team_1_toss = ["heads", "tails"].sample
    team_2_toss = ["heads", "tails"].sample
    team_3_toss = ["heads", "tails"].sample
    team_4_toss = ["heads", "tails"].sample

    #This will determine the attack results
    team_attack_1 = ["pass", "shoot"].sample
    team_attack_2 = ["dribble then shoot", "shoot from range"].sample
    team_attack_3 = ["pass", "shoot"].sample

    #This will determine the defend results
    team_defend_1 = ["slide tackle", "block tackle"].sample
    team_defend_2 = ["slide tackle", "block tackle"].sample
    team_defend_3 = ["slide tackle", "block tackle"].sample

    team_extra = ["shoot left", "shoot right"].sample

    team_1 = Teams.new("Barons", team_1_players, 0, team_1_captain, team_1_toss, team_attack_1, team_attack_2, team_attack_3, team_defend_1, team_defend_2, team_defend_3, team_extra)
    team_2 = Teams.new("Bandits", team_2_players, 0, team_2_captain, team_2_toss, team_attack_1, team_attack_2, team_attack_3, team_defend_1, team_defend_2, team_defend_3, team_extra)
    team_3 = Teams.new("Pepitas", team_3_players, 0, team_3_captain, team_3_toss, team_attack_1, team_attack_2, team_attack_3, team_defend_1, team_defend_2, team_defend_3, team_extra)
    team_4 = Teams.new("Scamps", team_4_players, 0, team_4_captain, team_4_toss, team_attack_1, team_attack_2, team_attack_3, team_defend_1, team_defend_2, team_defend_3, team_extra)

    teams_array = [team_1, team_2, team_3, team_4]
    game = Game.new("Football Shootout", "5-a-Side Football Sim", teams_array)
    return game
end


